name: Download and Sync Latest Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight (optional, can be removed if only manual trigger is needed)

jobs:
  sync-latest-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Get latest release info
      id: get_release
      run: |
        API_URL="https://api.github.com/repos/Zephyruso/zashboard/releases/latest"

        echo "Fetching latest release info from $API_URL"
        RELEASE_INFO=$(curl -s $API_URL)

        ASSET_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name == "dist.zip") | .browser_download_url')
        echo "Asset URL: $ASSET_URL"

        echo "::set-output name=asset_url::$ASSET_URL"

    - name: Download and unzip latest release
      run: |
        curl -L "${{ steps.get_release.outputs.asset_url }}" --output release.zip
        unzip -o release.zip -d release_content

    - name: Copy dist folder to current repository
      run: |
        cp -R release_content/* ./dist/

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./dist/
        git commit -m "Sync latest release dist folder"
        git push

    - name: Clean up
      run: |
        rm -rf release.zip release_content
